### ISSUE TITLE
Dll file

### ISSUE THREAD

**Issue by limelect** [fpiette/DelphiChatGPT#1]
![Screenshot - 07_01_2023 , 20_12_18](https://user-images.githubusercontent.com/4199131/211164731-179b89ad-fa54-4427-b64e-934e9f4d2544.jpg)
 can you include in the project the exact DLL's needed

**Comment by limelect** [comment]
I found both crypto and ssl .Nice it works now

**Comment by fpiette** [comment]
As you've found yourself, I Gave the explanation about the DLL in the source code.
If you need help don't create an issue here but visit: https://en.delphipraxis.net/forum/37-ics-internet-component-suite/
